# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
