manager:
  repeat_interval: 60 # seconds
  operation_timeout: 50 # seconds

unlocker:
  number_keys: 3
  request_timeout: 5
  # url: http://localhost:8200

encryption:
  path: "./tests/vault/data/"

storage:
  type: boltdb
  kubernetes:
    access: out-cluster
    namespace: monitoring
  boltdb:
    path: "./tests/vault/data/integration.db"

provisioner:
  mounts:
  - type: kv-v2
    path: cluster
    secrets:
      - path: smoke/test
        name: secret-name
        data:
          k1: v1
          k2: "*random*"

  policies:
    - name: external-secret-operator
      rules: |
        path "cluster/metadata/*" {
          capabilities = ["read"," list"]
        }
        path "cluster/data/*" {
          capabilities = ["read"," list"]
        }

  approles:
  - name: external-secret-operator
    policies:
      - external-secret-operator-policy
    secret_id_ttl: 0
    token_ttl: 3600
    token_max_ttl: 7200


