manager:
  repeat_interval: 60 # seconds
  operation_timeout: 50 # seconds

unlocker:
  number_keys: 3
  request_timeout: 5
  url: http://localhost:8200

encryption:
  path: "./tests/vault/data/"

storage:
  type: boltdb
  boltdb:
    path: "./tests/vault/data/integration.db"

provisioner:
  policies:
    - name: unlocker
      rules: |
        path "unlocker/data/*" { capabilities = [ "read", "list" ]}
        path "unlocker/metadata/*" { capabilities = [ "read", "list" ]}

    - name: external-secret-operator
      rules: |
        path "cluster/metadata/*" { capabilities = ["read","list"] }
        path "cluster/data/*" { capabilities = ["read","list"] }

  auth:
    - type: userpass
      path: userpass
      users:
        - name: unlocker
          pass: unlocker
          policies:
            - unlocker

    - type: kubernetes
      path: kubernetes

    - type: approle
      path: approle
      approles:
      - name: external-secret-operator
        policies:
          - external-secret-operator-policy
        secret_id_ttl: 3600
        token_ttl: 3600
        token_max_ttl: 7200
        export:
          namespace: security

  mounts:
  - type: kv-v2
    path: unlocker

  - type: kv-v2
    path: cluster
    secrets:
      - path: smoke/test
        name: secret-name
        data:
          k1: v1
          k2: "*random*"

exporter:
  kubernetes:
    access: out-cluster
