apiVersion: v2
name: vault
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.100.0"
dependencies:
  - name: vault
    version: 0.30.0
    repository: https://helm.releases.hashicorp.com
