vault:
  server:
    image:
      pullPolicy: IfNotPresent
    extraContainers:
      - name: vault-local-auto-unlocker
        image: danielnegreiros/vault-local-auto-unlocker:latest
        volumeMounts:
          - mountPath: /home/vaultmanager
            name: home-volume
    volumes:
      - name: home-volume
        persistentVolumeClaim:
          claimName: home-pvc
    service:
      type: NodePort
      nodePort: 30040
