vault:
  server:
    extraContainers:
      - name: vault-local-auto-unlocker
        image: danielnegreiros/vault-local-auto-unlocker:latest
        volumeMounts:
          - mountPath: /home/vaultmanager
            name: home-volume
    volumes:
      - name: home-volume
        persistentVolumeClaim:
          claimName: home-pvc
